[package]
name = "wtii"
version = "0.1.0"
authors = ["Olivier Dolle <olivier.dolle@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
confy = "*"
serde_derive = "*"
serde = "*"